language: android
android:
  components:
    - build-tools-19.0.3
    - android-19
    - extra-android-support





notifications:
  irc: "irc.freenode.org#shoes"
  email:
    recipients:
      - www.dingpengwei@gmail.com
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
